tskit-dev/tskit-site

- .gitignore
- _includes/software-list.html
- learn.html
Just a start, but probably better than what is currently there.
> Intro text

- .github/workflows/build-deploy.yml
Ha, caching made it look like everything worked. Trying again.
> Fix doc builds

- .github/workflows/build-deploy.yml
- Gemfile.lock
- _layouts/page.html
> Don't use make -C

- _includes/software-summary.html
- _layouts/software-page.html
> Switch to using tag name for releases

- Makefile
- _config.yml
- _plugins/doi_api.rb
- _plugins/github_api.rb
- learn.html
Closes #31 
Having an exhaustive list of all our publications isn't actually that helpful for someone getting started, so I cut it down to some the key ones and added some reading notes.
Hope I haven't mucked up the Ruby @benjeffery?
> Change to Key Publications

- learn.html
> Get links working

- .github/workflows/build-deploy.yml
> Remove env cache

- _software/1 - tsinfer.md
I suspect most people will want to read in data from a VCF, but this is complex and already covered in the tutorial, so the example code snippet in the PR assumes a file of the correct format, with the longer text directing people to the tutorial for how to create one from a VCF. Not sure if this is the right way to structure the info, but it has the virtue of being short and to the point
> Add example and brief description of tsinfer

- .github/workflows/build-deploy.yml
- .gitignore
- _software/pyslim.md
Closes #38.
But, what do we do to make the docs build?
Also: it's not really clear where to put pyslim - simulate? analyse?
> add pyslim

- .github/workflows/build-deploy.yml
> Fix slim docs

- _software/1-tskit.md
- _software/SLiM.md
In the blurb, I cut the bit about Eidos for brevity, but it could be reintroduced if we'd like more text.
> Slim snippet

- _software/1-tskit.md
- learn.html
Pining @petrelharp - does this help with #53 ?
> Change the Learn page to highlight tutorials

- learn.html
Ah, spotted the problem, and made the other contents more consistent.
> Close off the divs properly

- .github/workflows/build-deploy.yml
Build was failing as deploy didn't wait for pyslim.
> Add pyslim step to deploy deps

- index.html
This is a briefer mention than in the tskit readme (https://github.com/tskit-dev/tskit/pull/1941) but I think we don't want to make such a big deal of it here, just do a name-check.
> Mention ARGs in the introduction

- .github/workflows/build-deploy.yml
Um, I think this will work? But, i don't quite remember why it was commented out..
> add pyslim stable build

- .github/workflows/build-deploy.yml
> fix stable pyslim build

- google67572ac0f719e711.html
It would be good to get some insights into how Google views the tskit.dev site. This will let me get access to it on the search console. Others can also access if they are interested.
> Google site ownership verification

- .github/workflows/build-deploy.yml
Okay, I've released pyslim 1.0 so we need to put this back (already; sorry).
> latest slim

- _resources/completing-forward-sims.md
- _resources/getting-started.md
- _resources/msprime.md
> Fix tut links

- .github/workflows/build-deploy.yml
Adds tsinfer docs to tskit.dev! For now the stable docs will look like the old RTD docs.
> Build tsinfer docs

- _resources/wong-phyloseminar.md
- learn.html
I assume we can do this @benjeffery ?
> Add description to a video

- .github/workflows/build-deploy.yml
- _resources/tskit-rust.md
- learn.html
> Add rust tut to deploy

- .github/workflows/build-deploy.yml
Closes #76 which I think was out of date, but there is some tsinfer cruft to clean up anyway.
> Remove unneeded tsinfer build lines

- _includes/software-summary.html
- _layouts/software-page.html
- _software/SLiM.md
> Add slim website

- genetics-research.html
When https://github.com/tskit-dev/tutorials/pull/209 is merged
> Link to new popgen tutorial

- .github/workflows/build-deploy.yml
> Downgrade pip to get tskit docs built

- learn.html
> Minor typo

- .github/workflows/build-deploy.yml
> initial version of tstrait docs

- .github/workflows/build-deploy.yml
> Enable tstrait stable docs

- .github/workflows/build-deploy.yml
Fixes #187 
Patch up the tsinfer docs, fixing the code style issue on the stable docs.
> Fix tsinfer build

- .github/workflows/build-deploy.yml
> Redirect tstrait

- _news/20231225-msprime-1.3.0.md
First draft for a news item on the upcoming msprime release.
> news item: msprime 1.3 release

- _resources/arg-paper.md
- _resources/wong2024.md
- _software/fwdpy11.md
> Minor tweaks to formatting and URLs

- _software/tspop.md
> Add a description of tspop

- .github/workflows/build-deploy.yml
> Update deploy action

- _resources/lewanski.md
> Add Lewanski review

- Gemfile
- Gemfile.lock
- _includes/navbar.html
- _includes/software-citation.html
- _software/msprime.md
- _software/pyslim.md
- _software/tsbrowse.md
- _software/tsdate.md
- _software/tsinfer.md
- _software/tskit.md
- _software/tstrait.md
- citations.html
> feat: 246 add citation page
